project:
    type: website
    output-dir: _site

website:
    title: "Data Analysis & Interpretation Log"
    description: "Coursework & progress for Wesleyan Data Analysis and Interpretation Specialization"
    site-url: "https://tariq-k-dev.github.io/wesleyan-data-analysis"
    favicon: favicon.png
    navbar:
        title: "Data Analysis Log"
        left:
            - text: "Home / Posts"
              href: index.qmd
        right:
            - icon: github
              aria-label: GitHub Repository
              href: https://github.com/tariq-k-dev/wesleyan-data-analysis
    page-footer:
        center: '© <span id="year"></span> Tariq Khan. All rights reserved.'

format:
    html:
        theme:
            light: cosmo
            dark: darkly
        toc: true
        code-fold: show
        code-tools: true
        df-print: paged
        include-after-body: footer-year.html

execute:
    freeze: auto
